Glover/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('Glover_main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Glover_main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 사용자 페이지
	path('', main, name='main'),
    path('search/', main, name='search'),
    
    # 관리자 페이지
    path('a_main/', a_main, name='a_main'),
    path('a_events/', a_events, name='a_events'),
    path('a_add/', a_add, name='a_add'),
    path('a_search/',a_search,name='a_search'),
    path('edit_stamp/<str:event_name>/', edit_stamp, name='edit_stamp'),
    path('delete_stamp/<str:event_name>/', delete_stamp, name='delete_stamp'),
    
    # 
    path('introduce/', introduce, name='introduce'),
    path('makers/', makers, name='makers'),
    # path('edit_X_check/', edit_X_check, name='edit_X_check'),
    # path('edit_save_check/', edit_save_check, name='edit_save_check'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Glover_main/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class stamp(models.Model):
    event_name = models.CharField(max_length=200, primary_key=True)
    event_info = models.TextField()
    event_start = models.DateField()
    event_end = models.DateField()
    image = models.ImageField(upload_to='images/')
    
    def __str__(self):
        return self.event_name


class stamp_collection(models.Model):
    student = models.ForeignKey('student', on_delete=models.CASCADE)
    stamp = models.ForeignKey(stamp, on_delete=models.CASCADE)
    is_collected = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.student} - {self.stamp}'


class student(models.Model):
    student_id = models.CharField(max_length=20, primary_key=True)
    full_name = models.CharField(max_length=20)
    major = models.CharField(max_length=100)
    grade = models.IntegerField()
    consent = models.BooleanField(default=False)
    
    stamps = models.ManyToManyField(stamp, through='stamp_collection', related_name='collectors')
    
    def __str__(self):
        return f'{self.student_id} - {self.major} - {self.full_name} - {self.consent}'
    
    
# stamp추가할 때마다 중계모델에 추가
@receiver(post_save, sender=stamp)
def create_stamp_collection(sender, instance, **kwargs):
    students = student.objects.all()
    
    for student_instance in students:
        stamp_collection.objects.create(student=student_instance, stamp=instance)
        
        
# 학생 추가되면 기존 스탬프 추가
@receiver(post_save, sender=student)
def create_student_stamp_collection(sender, instance, created, **kwargs):
    if created:
        stamps = stamp.objects.all()
    
        for stamp_instance in stamps:
            stamp_collection.objects.get_or_create(student=instance, stamp=stamp_instance)

Glover_main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import student, stamp, stamp_collection
from django.http import HttpResponse
from django.contrib.sessions.models import Session
from django.db import transaction
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os
from django.http import JsonResponse
from urllib.parse import unquote
from django.urls import reverse

# Create your views here.
# 메인페이지
def main(request, student_id=None):
    if request.method == 'POST':
        student_id = request.POST.get('student_id')
        major = request.POST.get('major')

        student_info = student.objects.get(student_id=student_id, major=major)
        stamp_collections = stamp_collection.objects.filter(student=student_info)

        agreed = student.objects.get(student_id=student_id)
        agreed.consent = True
        # is_agreed = agreed.consent
        # print(is_agreed)

        # 'search' URL 패턴에 대한 URL 생성
        search_url = reverse('search')
        
        return render(request, 'user_page/search.html', {'student_info': student_info, 'stamp_collections':stamp_collections, 'agreed': agreed})

    return render(request, 'user_page/index.html')


# ?
def search(request):
    student_id = request.GET.get('student_id', '')
     # 데이터베이스에서 학번을 사용하여 학생 객체를 가져옵니다.
    student_obj = get_object_or_404(student, student_id=student_id)
    # 학생 객체에서 이름을 추출합니다.
    full_name = student_obj.full_name
    
    # 학번과 이름을 템플릿으로 전달
    context = {
        'student_id': student_id,
        'full_name':full_name,
    }

    return render(request, 'user_page/search.html', context)


def update_consent(request):
    if request.method == 'POST':
        student_id = request.POST.get('student_id')
        student = student.objects.get(student_id=student_id)
        
        # 최초 동의 필드를 업데이트
        student.consent = True
        student.save()
        
        return JsonResponse({'message': '동의가 업데이트되었습니다.'})
    else:
        return JsonResponse({'message': 'POST 요청이 아닙니다.'}, status=400)


# 동의 업뎃
# def check_consent(request):
#     if request.method == 'GET':
#         # 여기에서 사용자의 consent 상태를 확인하고 값을 가져옵니다.
#         # 예를 들어, 현재 로그인한 사용자의 consent 상태를 확인할 수 있습니다.
#         user = request.student
#         consent_status = user.profile.consent  # 사용자 프로필에 consent 필드가 있다고 가정

#         return JsonResponse({'consent_status': consent_status})
#     else:
#         return JsonResponse({'error': 'GET 요청이 아닙니다.'})

# 서비스 소개
def introduce(request):
	return render(request, 'user_page/introduce.html')


# 만든이들
def makers(request):
	return render(request, 'user_page/makers.html')


# 관리자 페이지
def a_main(request):
	return render(
		request,
		'admin_page/a_main.html'
	)


# stamp 추가
def a_add(request):
    if request.method == 'POST':
        event_name = request.POST['event_name']
        event_info = request.POST['event_info']
        event_start = request.POST['event_start']
        event_end = request.POST['event_end']
        image = request.FILES.get('after_image') if 'after_image' in request.FILES else None

        # 데이터 유효성 검사 및 저장
        if event_name and event_info and event_start and event_end and image:
            mystamp = stamp (
                event_name = event_name,
                event_info = event_info,
                event_start = event_start,
                event_end = event_end,
                image = image,
            )
            mystamp.save()
            return redirect('stamp_list')
        else:
            # 필요한 모든 데이터가 제출되지 않은 경우에 대한 처리
            error_message = "모든 필드를 입력해야 합니다."
    else:
        error_message = ""

    return render(request, 'admin_page/a_add.html', {'error_message': error_message})


# stamp 리스트
def a_events(request):
    stamps = stamp.objects.all()
    return render(request, 'admin_page/a_events.html', {'stamps': stamps})


#이벤트 참여자 체크하는 페이지
def a_search(request):
    events = stamp.objects.all()
    students = student.objects.all()
    selected_event = None

    if request.method == 'POST':
        event_name = request.POST.get('event_name')
        major = request.POST.get('major')
        student_id = request.POST.get('student_id')

        if event_name:
           selected_event = stamp.objects.get(event_name=event_name)

        if major:
           students = students.filter(major=major)

        if student_id:
           students = students.filter(student_id__icontains=student_id)
        
        # 선택된 이벤트의 체크박스 확인 후 해당 학생의 student_collection을 업데이트
        event_check1 = request.POST.getlist('hiddenInput')
        event_check2 = request.POST.getlist('hiddenInput2')
        
        for stamp_collection_id, is_collected_str in zip(event_check2, event_check1):
            try:
                # is_collected_str 값을 불리언 값으로 변환하여 사용
                is_collected = is_collected_str.lower() == 'true'

                collection = stamp_collection.objects.get(id=stamp_collection_id)

                collection.is_collected = is_collected
                collection.save()
            except:
                pass
        # print(students)
        if student_id:
            stamp_collections = stamp_collection.objects.filter(student__student_id__icontains=student_id, stamp=selected_event)
        else:
            # student_id가 None이면 stamp_collections를 빈 쿼리셋으로 초기화
            stamp_collections = stamp_collection.objects.none()

        context = {'students': students, 
                   'events': events, 
                   'initial_data': request.POST, 
                   'stamp_collections':stamp_collections,
                   }

        return render(request, 'admin_page/a_search.html', context)

    return render(request, 'admin_page/a_search.html', {'events': events, 'students': students})


# 스탬프 수정
@transaction.atomic
def edit_stamp(request, event_name):
    stamp_instance = get_object_or_404(stamp, event_name=event_name)
    
    if request.method == 'POST':
        # POST 데이터에서 가져와서 업데이트
        updated_data = {'event_name': request.POST.get('event_name'),
                        'event_info': request.POST.get('event_info'),
                        'event_start': request.POST.get('event_start'),
                        'event_end': request.POST.get('event_end')}
    
        # 이미지 업데이트 처리
        before_image = request.FILES.get('before_image')
        if before_image:
            # FileSystemStorage사용하여 이미지 저장
            fs = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'before_images'))
            filename = fs.save(before_image.name, before_image)
            updated_data['before_image'] = filename
        
        after_image = request.FILES.get('after_image')
        if after_image:
            fs = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'after_images'))
            filename = fs.save(after_image.name, after_image)
            updated_data['after_image'] = filename
            
        # DB에 직접 업뎃
        stamp.objects.filter(event_name=event_name).update(**updated_data)
        return redirect('stamp_list')  # 수정 후 도장 목록으로 리디렉션
        
    return render(request, 'admin_page/edit_stamp.html', {'stamp_instance': stamp_instance})


# stamp 삭제
def delete_stamp(request, event_name):
    delstamp = get_object_or_404(stamp, event_name=event_name)
    
    if request.method == 'POST':
        # Store the post pk before deleting the comment
        delstamp.delete()
        return redirect('stamp_list')
    return render(request, 'admin_page/a_events.html', {'delstamp': delstamp})


# stamp 정보 보기
def info_stamp(request, event_name):
    event_name = unquote(event_name)
    # 스탬프 정보 가져오기
    stamp_instance = get_object_or_404(stamp, event_name=event_name)
    
    return render(request, 'main_page/info_stamp.html', {'stamp_instance': stamp_instance})


# X버튼 확인
# def edit_X_check(request):
# 	return render(request, 'manager_page/edit_X_check.html')


# # 저장하시겠습니까
# def edit_save_check(request):
# 	return render(request, 'manager_page/edit_save_check.html')

Glover_main/templates/admin_page/a_add.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 Lover</title>
    <link rel="stylesheet" href={% static "css/a_add.css" %}>
    <script src={% static "js/a_add.js" %} defer></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- font awesome 연결링크 -->
    <script src="https://kit.fontawesome.com/855cb859ed.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="display-container header-font">
        <!-- navbar section -->
        <nav>
            <div class="navbar jamsil-font">
                <div class="container nav-container">
                    <div class="nav_logo">
                        <a href={% url 'a_main'%}>
                            <img src={% static "images/gloverlogo.png"%} alt="">
                        </a>
                    </div>
                    <input class="checkbox" type="checkbox" name="" id="" />
                    <div class="hamburger-lines">
                        <span class="line line1"></span>
                        <span class="line line2"></span>
                        <span class="line line3"></span>
                    </div>  
                    <div class="menu-items">
                        <div class="menu_durumari d-flex flex-column text-center">
                            <div class="menu_logo text-center">
                                <img src={% static "images/gloverlogo.png"%} alt="">
                            </div>
                            <p class="tmoney font-bold">청천(靑天)</p>
                            <p class="tmoney">글로벌경영기술대학</p>
                            <div class="menu_line"></div>
                            <li><a href={% url 'a_events' %}><p class="shilla">이벤트 관리</p><br /></a></li>
                            <li><a href={% url 'a_search' %}><p class="shilla">이벤트 참여자 조회</p></a></li>
                            <div class="menu_line"></div>
                            <div class="menu_footer">
                                <div class="firstline d-flex justify-content-center">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cloud" viewBox="0 0 16 16" style="color : #758DBB">
                                        <path d="M4.406 3.342A5.53 5.53 0 0 1 8 2c2.69 0 4.923 2 5.166 4.579C14.758 6.804 16 8.137 16 9.773 16 11.569 14.502 13 12.687 13H3.781C1.708 13 0 11.366 0 9.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383zm.653.757c-.757.653-1.153 1.44-1.153 2.056v.448l-.445.049C2.064 6.805 1 7.952 1 9.318 1 10.785 2.23 12 3.781 12h8.906C13.98 12 15 10.988 15 9.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 4.825 10.328 3 8 3a4.53 4.53 0 0 0-2.941 1.1z"/>
                                      </svg>
                                    <p class="tmoney">제 2대 그대를 빛낼 하늘, 청천(靑天)</p>
                                </div>
                                <div class="secondline d-flex justify-content-center">
                                    <p class="tmoney">글로벌경영기술대학 학생회</p>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-brightness-high-fill" viewBox="0 0 16 16" style="color : #758DBB">
                                        <path d="M12 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
                                    </svg>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <!-- header section -->
        <div class="header_title">
            <p class="header_name">도장 추가</p>
            <p class="header_sub">글천절</p>
            <p class="header_add">: 글Lover</p>
            <div class="background_img">
                <img src={% static "images/cloud.png"%} alt="구름2" class="cloud1">                
                <img src={% static "images/cloud.png"%} alt="구름2" class="cloud2">
                <img src={% static "images/cloud.png"%} alt="구름3" class="cloud3">
                <!-- <img src="../../img/cloud.png" alt="구름4" class="cloud4"> -->
            </div>
        </div>
        <!-- main section -->
        <div id="modal">
            <div class="modal-bg">
                <div class="modal-cont">
                    <div class="modal-head">
                        <input class="header-font" type="text" name="event_name" id="id_event_name" placeholder="사업명" autofocus>
                        <button class="bi-x">
                            <svg width="15" height="15" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M11.8334 1.3415L10.6584 0.166504L6.00008 4.82484L1.34175 0.166504L0.166748 1.3415L4.82508 5.99984L0.166748 10.6582L1.34175 11.8332L6.00008 7.17484L10.6584 11.8332L11.8334 10.6582L7.17508 5.99984L11.8334 1.3415Z" fill="#758DBB"/>
                            </svg>
                        </button>
                    </div>
                    <div class="modal-bar"></div>
                    <!-- from section  -->
                    <form method='post' class="tmoney-font" enctype="multipart/form-data">
                        {% csrf_token %}
                        <textarea class="detail" type="text" name="event_info" id="id_event_info" placeholder="설명"></textarea>
                        <br>
                        <!-- date -->
                        <p class="term header-font">기간</p>
                        <div class="date">
                            <input type="date" name="event_start" id="id_event_start">~<input type="date" name="event_end" id="id_event_end">
                        </div>
                        <div class="modal-bar2 text-center"></div>
                        <!-- file upload -->
                        <p class="term header-font">스탬프 이미지</p>
                        <div class="img">
                            <div class="file-box">
                                <input type="file" name="after_image" id="after_image" accept=".jpg, .jpeg, .png, .gif" onchange="readURL(this, 'preview_after');" required/>
                                <img id="preview_after" class="img-box" />
                            </div>
                        <!-- button -->
                        <div class="button">
                            <button type="submit" class="submit" id="submit">저장</button>
                            <button class="del" type="button">삭제</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- second modal section 
        <div class="sec_modal" id="fir_modal">
            <div class="sec_modal_content">
                <p class="sec_header">
                    저장하시겠습니까?
                </p>
                <div class="modal_button">
                    <a href="#" class="yes"><button>예</button></a>
                    <a href="#" class="no"><button>아니요</button></a>
                </div>
            </div>
        </div>
        <div class="sec_modal" id="sec_modal">
            <div class="sec_modal_content">
                <p class="sec_header">
                    삭제하시겠습니까?
                </p>
                <div class="modal_button">
                    <a href="#" class="yes"><button>예</button></a>
                    <a href="#" class="no"><button>아니요</button></a>
                </div>
            </div>
        </div>
        <div class="sec_modal" id="thi_modal">
            <div class="sec_modal_content">
                <p class="sec_header">
                    저장하지않고<br> 나가시겠습니까?
                </p>
                <div class="modal_button">
                    <a href="#" class="yes"><button>예</button></a>
                    <a href="#" class="no"><button>아니요</button></a>
                </div>
            </div>
        </div> -->
        <!-- footer section -->
        <div class="footer-section jamsil-font">
            <div class="firstline d-flex justify-content-center ">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cloud" viewBox="0 0 16 16">
                    <path d="M4.406 3.342A5.53 5.53 0 0 1 8 2c2.69 0 4.923 2 5.166 4.579C14.758 6.804 16 8.137 16 9.773 16 11.569 14.502 13 12.687 13H3.781C1.708 13 0 11.366 0 9.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383zm.653.757c-.757.653-1.153 1.44-1.153 2.056v.448l-.445.049C2.064 6.805 1 7.952 1 9.318 1 10.785 2.23 12 3.781 12h8.906C13.98 12 15 10.988 15 9.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 4.825 10.328 3 8 3a4.53 4.53 0 0 0-2.941 1.1z"/>
                  </svg>
                <p>제 2대 그대를 빛낼 하늘, 청천(靑天)</p>
            </div>
            <div class="secondline d-flex justify-content-center">
                <p>글로벌 경영기술대학 학생회</p>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-brightness-high-fill" viewBox="0 0 16 16">
                    <path d="M12 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
                </svg>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>